############### Complete Home Control Compose ###############

version: '3.7'
services:

########## Container Management ##########

##### Watchtower

 watchtower:
  container_name: watchtower
  image: containrrr/watchtower:armhf-latest
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  command: hass homebridge tvheadend --debug --cleanup

########## Web Server/Reverse Proxy ##########

##### NGINX - Reverse Proxy

 nginx:
  container_name: nginx
  image: tobi312/rpi-nginx
  labels: 
   - com.centurylinklabs.watchtower.enable= "false"
  restart: always
  ports:
   - 80:80
   - 443:443
  environment:
   - TZ=${TZ}
   - PGID=${PGID}
   - PUID=${PUID}
  links:
   - php
   - hass
   - tvheadend
  volumes:
   - $HOME/docker/nginx/config:/etc/nginx/conf.d:ro
   - $HOME/docker/nginx/html:/var/www/html
   - /etc/letsencrypt:/etc/letsencrypt

##### PHP - PHP Service

 php:
  container_name: php
  image: tobi312/rpi-php
  restart: always
  ports:
   - 9000:9000
  environment:
   - TZ=${TZ}
   - PGID=${PGID}
   - PUID=${PUID}
   - PHP_ERRORS=1
   - PHP_UPLOAD_MAX_FILESIZE=250
  volumes:
   - $HOME/docker/nginx/html:/var/www/html

########## Smart Home Services ##########

##### Home Assistant - Smart Home Control System

 hass:
  container_name: hass
  image: homeassistant/raspberrypi3-homeassistant:latest
  restart: always
  ports:
   - 8123:8123
  network_mode: host
  privileged: true
  environment:
   - TZ=${TZ}
   - PGID=${PGID}
   - PUID=${PUID}
  devices:
   - "/dev/ttyUSB0:/dev/ttyUSB0"
  volumes:
   - $HOME/docker/hass:/config

##### Homebridge - Homekit Bridge

 homebridge:
  container_name: homebridge
  image: oznu/homebridge:raspberry-pi
  restart: always
  network_mode: host
  environment:
   - TZ=${TZ}
   - PGID=${PGID}
   - PUID=${PUID}
   - HOMEBRIDGE_CONFIG_UI=1
   - HOMEBRIDGE_CONFIG_UI_PORT=8080
  volumes:
   - $HOME/docker/homebridge:/config

########## LiveTV - DTV & Sports Streams ##########

##### TVHeadend - TV Software

 tvheadend:
  container_name: tvheadend
  image: linuxserver/tvheadend:arm32v7-latest
  restart: always
  network_mode: "host"
  environment:
   - TZ=Europe/London
   - PGID=${PGID}
   - PUID=${PUID}
  volumes:
   - $HOME/docker/tvheadend:/config
   - $HOME/docker/tvheadend/picons:/picons
